### ISSUE TITLE
NullPointerException on player join

### ISSUE THREAD

**Issue by ChefMC** [RhysB/Discord-Bot-Chatbridge#1]
```
20:36:43 [INFO] PalPalycz [/***.***.***.***:16795] logged in with entity id 154 at ([world] 130.90625, 66.0, -136.3125)
20:36:43 [SEVERE] Could not pass event PLAYER_JOIN to DiscordBot
java.lang.NullPointerException
        at com.johnymuffin.discordbot.DiscordBot.execute(DiscordBot.java:138)
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
        at net.minecraft.server.ServerConfigurationManager.c(ServerConfigurationManager.java:118)
        at net.minecraft.server.NetLoginHandler.b(NetLoginHandler.java:97)
        at net.minecraft.server.NetLoginHandler.a(NetLoginHandler.java:33)
        at net.minecraft.server.NetworkListenThread.a(SourceFile:91)
        at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:463)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:372)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:422)
```

![изображение](https://user-images.githubusercontent.com/3519015/62910903-0300d200-bd8b-11e9-81cd-9dc9d30a8576.png)

I sure null returns `this.discord` or `this.discord.Discord()` (because args can be null)

**Comment by RhysB** [comment]
Hey, i was unable to recreate the issue.
Is the channel provided, and a login and quit template, and is this only occurring with Join Messages?
Can you add me on Discord: Johny Muffin#9406 as it will be easier to help in real time.

**Comment by ChefMC** [comment]
It was a once (single) error. All works fine since it was caused (and before too)
